services:
  mongo:
    image: "mongo:latest"
    container_name: "mongoJolt"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmqJolt"
    ports:
      - "5672:5672"      # Port pour les connexions applicatives
      - "15672:15672"    # Port pour l'interface de management web
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  redis:
    image: "redis:latest"
    container_name: "redisJolt"
    ports:
      - "6379:6379"
volumes:
  mongo-data: