name: Build & Push all microservices

on:
  push:
    branches: [main]
    paths:
      - '**/Dockerfile'
      - '.github/workflows/docker-microservices.yml'
      - '**/*.js'
      - '**/package.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - mail
          - auth
          - users
          - gateway
          - vehicles
          - maintains
          - navigate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repo owner lowercase
        id: repo_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.owner }}/${{ matrix.service }}:latest
